### ISSUE TITLE
Not working with blazor version 3.0.0-preview5-19227-01

### ISSUE THREAD

**Issue by sukeshchand** [cloudcrate/BlazorStorage#12]
The library is not working 3.0.0-preview5-19227-01.

**Comment by LunicLynx** [comment]
Please check that you have the latest preview. And use it with preview5 of net core.

Also clean and rebuild your Project after updating. Sometimes the js files are not replaced correctly (an issue of Blazor).

Let me know if this doesn’t work

**Comment by kevinjpetersen** [comment]
Hi @LunicLynx 

I'm having the same issue. Here's the errors I'm getting:

`AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage Lifetime: Singleton ImplementationType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage'.) (Error while validating the service descriptor 'ServiceType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.SessionStorage Lifetime: Singleton ImplementationType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.SessionStorage': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Cloudcrate.AspNetCore.Blazor.Browser.Storage.SessionStorage'.)`

`InvalidOperationException: Error while validating the service descriptor 'ServiceType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage Lifetime: Singleton ImplementationType: Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Cloudcrate.AspNetCore.Blazor.Browser.Storage.LocalStorage'.`

**Comment by LunicLynx** [comment]
Strange I don’t have this issue.

A workaround would be to change the:

services.AddStorage()

to

‘services.AddScoped<LocalStorage>()‘
‘services.AddScoped<SessionStorage>()‘
