### ISSUE TITLE
Incompatibility with Blazor Preview 9

### ISSUE THREAD

**Issue by CobraCalle** [cloudcrate/BlazorStorage#18]
Hi,

in Blazor Preview 9 the signature of the method to call client side javascript has changed, so we get an error when we try to access the local storage.

The paramters to the javascript call over JsRuntimeInvokeAsync have to be an object array now and it returns a ValueTask<T> instead of Task<T>

Carl

**Comment by LunicLynx** [comment]
I’ll push an update later today

**Comment by LunicLynx** [comment]
Pushed

**Comment by LunicLynx** [comment]
3.0.0-preview9.19424.4.2
