### ISSUE TITLE
Not compatible with 0.5 version

### ISSUE THREAD

**Issue by rafek1241** [cloudcrate/BlazorStorage#2]
Not compatible with 0.5 version of blazor. Have a nice day :)

**Comment by LunicLynx** [comment]
Thanks for the info. I pushed a preview 0.5.0-preview1, which should be compatible.
Please try that one.
Also if it doesn't work for you, can you please provide the error you get?
Thanks!

**Comment by LunicLynx** [comment]
fixed in 0.5.0-preview2
