### ISSUE TITLE
[Dotnet Core 3.0.100] Could not find 'Cloudcrate_AspNetCore_Blazor_Browser_Storage_LocalStorage' in 'window' error

### ISSUE THREAD

**Issue by davidsaurel** [cloudcrate/BlazorStorage#21]
Hello thanks for your work.

I encounter the error in server side app ```
Error: Microsoft.JSInterop.JSException: Could not find 'Cloudcrate_AspNetCore_Blazor_Browser_Storage_LocalStorage' in 'window'.
Error: Could not find 'Cloudcrate_AspNetCore_Blazor_Browser_Storage_LocalStorage' in 'window'.
```
Thanks

**Comment by LunicLynx** [comment]
Did you follow the installation steps?

In particular 

This:
<script src="_content/Cloudcrate.AspNetCore.Blazor.Browser.Storage/Storage.js"></script>

**Comment by davidsaurel** [comment]
Yes sorry, read too fast
