### ISSUE TITLE
Cookie storage fallback

### ISSUE THREAD

**Issue by ghidello** [cloudcrate/BlazorStorage#6]
Hi, I just saw this issue https://github.com/IdentityModel/oidc-client-js/issues/631 where they are trying to have some sort of persistence when local and session storage are not available (e.g. chrome incognito mode). Do you think we should provide this kind of fallback?

**Comment by LunicLynx** [comment]
Interesting!
Supporting storing data in cookies would be really nice. The fallback on the otherhand is probably best handled by the library consumer, hard to make assumptions about the consumers intent.

**Comment by ghidello** [comment]
Sorry if I didn't get back to you sooner. I agree that a library should not make assumptions on the consumer intent but I guess that I would like some way to opt-in a working solution for the fallback for those applications that must rely on some king of storage present. I'm actually working on a library which uses yours so I'll get back to you when I'll tackle the problem.

In the meantime thanks again: I'm loving my session storage so far!

**Comment by LunicLynx** [comment]
Closing as out of scope
