### ISSUE TITLE
Error with Blazor 0.8.0

### ISSUE THREAD

**Issue by FrankNNDK** [cloudcrate/BlazorStorage#8]
'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

'BlazorWebAssemblyHost' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.5.1.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by LunicLynx** [comment]
@FrankNNDK Thanks for reporting. This library has not been updated to Blazor 0.8.0 yet. Maybe this is working for you in the meantime: 
https://github.com/BlazorExtensions/Storage

**Comment by FrankNNDK** [comment]
> @FrankNNDK Thanks for reporting. This library has not been updated to Blazor 0.8.0 yet. Maybe this is working for you in the meantime:
> https://github.com/BlazorExtensions/Storage

@LunicLynx  I think BlazorExtensions has the same. blazorExtensions use 0.7.0 ?

'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.8.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by LunicLynx** [comment]
@FrankNNDK I see, I'll have a look later to-day/-night. 
To be honest, haven't really been involved with Blazor since this Razor Components stuff happened.

**Comment by McHeff** [comment]
Please leave an update if you get this working @LunicLynx

**Comment by McHeff** [comment]
There's a discord server if you guys are interested: https://discord.gg/Xg9ja5s

**Comment by LunicLynx** [comment]
Released an update for blazor 0.9.0

**Comment by McHeff** [comment]
Awesome, well done!
