### ISSUE TITLE
Add StorageEvent support

### ISSUE THREAD

**Issue by peterblazejewicz** [cloudcrate/BlazorStorage#9]
Common use-case is to synchronize information between multiple tabs of the same app (like last selected top level feature within an app).
https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-event

Let me know if you want that feature introduced,
Thanks

**Comment by LunicLynx** [comment]
Sounds great! Are you working on it?

**Comment by peterblazejewicz** [comment]
probably, I started my own deeper insight into Blzr. Could do this at some point, leave open.
Thanks!

**Comment by LunicLynx** [comment]
Completed with #11, Thanks @peterblazejewicz !
